src/actions/graph.ts
src/components/editor/systemNode.tsx
src/controller/oscqueryBridgeController.ts
src/models/graph.ts
src/selectors/graph.ts

As discussed in #48 this parses the Jack info by filtering out the port names used for instances rather than relying upon `system` and `system_midi` being used as jack names to allow more generic system node support

More generic System node creation

---

src/actions/graph.ts

Prior to this system nodes were stating off with negative x-coordinates

Zero based node coordinates

---

src/components/editor/editor.module.css
src/components/editor/index.tsx

* ColorScheme support for react-flow attribution and controls
* double clicking a patcher node navigates to device control

Minor Graph Editor tweaks

---

src/components/parameter/item.tsx
src/lib/types.ts
src/models/parameter.ts

This adds slider markers and stepped movement for enum parameters.
One thing I noticed is that `[param]` objects without `@min` and `@max` basically default to a 0 - 1 range and seem to report their value within that range only. Maybe expected due to the lack of more info and the "fix" is to recommend setting the min and max attributes but thought I'd mention
Closes #61

Improved enum parameter handling

---

src/actions/graph.ts
src/components/editor/controlNode.tsx
src/components/editor/index.tsx
src/controller/oscqueryBridgeController.ts
src/lib/types.ts
src/models/graph.ts
src/selectors/graph.ts

added support for ControlNodes aka non-system, non-patcher nodes

---

src/actions/graph.ts
src/components/editor/patcherNode.tsx
src/models/graph.ts

This adds the instance's index to an instance node in the graph view and improves the system node placement for a bit more space. The latter is more of a cosmetic tweak after the widened system nodes for improved I/O naming rather than an elaborate algorithm to calculate the positions but should be enough for now to make it more usable from the get go.

Minor tweak to Graph Editor Display

---

src/components/page/statusWrapper.tsx
src/controller/oscqueryBridgeController.ts
src/lib/constants.ts
src/lib/types.ts

I'm thinking I might make the runner re-send the activated message after the audio actually activates.. the issue is that a user can deactivate audio and then reactivate and we get a `true` sent out before the audio is fully active.. so i have a sleep in there for now.

allow for audio to be off

---

src/actions/appStatus.ts
src/components/header/index.tsx
src/components/page/endpoint.tsx
src/components/page/statusWrapper.tsx
src/controller/oscqueryBridgeController.ts
src/lib/types.ts
src/models/runnerInfo.ts
src/reducers/appStatus.ts
src/selectors/appStatus.ts

First pass at including some display only info. Drilled open the connection modal and added a CPU meter to the header. Noticed that there isn't a dynamic stream of CPU load info incoming, maybe that's by the design and the frontend / client is supposed to poll that?
Let me know if you need help plumbing this together :D If the client should poll the cpu load it's not really a big deal and we could also add a user setting to enable / disable that.
closes #116

Show Runner info (CPU | xrun)

---

package-lock.json
package.json
src/components/instance/datarefTab.tsx
src/components/sets/index.tsx
src/pages/index.tsx
src/selectors/datafiles.ts
src/selectors/patchers.ts
src/selectors/sets.ts
src/selectors/settings.ts

With the introduction of a constantly updating state (cpu load display) some of the derived state was simply being recalculated on every state change. This introduces memoized selectors for calculated state access results
fixes #134

Memoized derived state selectors

---

src/actions/instances.ts
src/actions/sets.ts
src/components/editor/controlNode.tsx
src/components/editor/index.tsx
src/components/editor/patcherNode.tsx
src/components/editor/systemNode.tsx
src/components/editor/util.ts
src/components/instance/datarefTab.tsx
src/components/instance/index.tsx
src/components/instance/paramTab.tsx
src/components/page/theme.tsx
src/components/sets/index.tsx
src/hooks/useTheme.ts
src/pages/index.tsx
src/pages/instances/[index].tsx
src/reducers/sets.ts
src/selectors/appStatus.ts
src/selectors/datafiles.ts
src/selectors/graph.ts
src/selectors/instances.ts
src/selectors/notifications.ts
src/selectors/patchers.ts
src/selectors/sets.ts
src/selectors/settings.ts

We were still running quite a few unnecessary render flushes so I took a slight dive to extend the memoized selection and reduced the `useAppSelector` usage to top level comps and pages

State Optimization

---

src/actions/graph.ts

closes #119 
one issue is that when we clear the graph or delete a node, we don't clear out the meta for that/those nodes.. but, we do once we move a node so I figure in practice that shouldn't get in the way too often... hooking up the logic to transmit the meta after a node pops up felt a little brittle.

simply position nodes without meta at 0, 0

---

src/actions/instances.ts
src/components/meta/metaEditorModal.module.css
src/components/meta/metaEditorModal.tsx
src/components/page/theme.tsx
src/lib/util.ts
src/models/parameter.ts
src/pages/_app.tsx

Stricter Parameter Meta Parsing

---

src/components/editor/port.tsx

I goofed on the regex with the last commit. This should apply the substitution for all capture/playback port numbers, not just 0-9

fix regex for port numbers > 9

---

src/components/editor/controlNode.tsx
src/components/editor/editor.module.css
src/components/editor/patcherNode.tsx
src/components/editor/port.tsx
src/components/editor/systemNode.tsx
src/components/editor/util.ts

Added styles and code to deal with long port names by clipping the label with an ellipsis and adding hover highlighting styles
See example screenshots attached
closes #173 
ee ex

graph editor: limit port label size and added on hover styles

---

package-lock.json
package.json
src/actions/editor.ts
src/actions/graph.ts
src/components/editor/controlNode.tsx
src/components/editor/editor.module.css
src/components/editor/index.tsx
src/components/editor/patcherNode.tsx
src/components/editor/systemNode.tsx
src/components/editor/util.ts
src/components/elements/icon.tsx
src/lib/constants.ts
src/models/graph.ts
src/pages/index.tsx
src/reducers/editor.ts
src/reducers/index.ts
src/selectors/editor.ts

This moves some of the viewport / editor pane interactions into actions & the state. The version of Reactflow we use doesn't fully support a controlled viewport but this gets us there.
Note that with this PR:
* the built-in controls menu is replaced with a custom one to also feature the layouting button
* we introduce an auto-layout functionality
* width & height of all nodes are controlled in the graph (but not resizable just yet)
* new patcher nodes should be placed in 0,0 of the current viewport
The migration of existing sets might be a bit clumsy due to the state controlled width & height but hopefully the auto-layout makes this smoother and easier to deal with?!
see #168
Also created #187 for node resizing

Patcher Node placement & Auto Layouting

---

src/actions/patchers.ts
src/components/editor/patcherNode.tsx
src/components/elements/editableTableCell.tsx
src/components/elements/elements.module.css
src/components/elements/tableHeaderCell.tsx
src/components/instance/paramTab.tsx
src/components/messages/inport.tsx
src/components/messages/outport.tsx
src/components/meta/metaEditorModal.tsx
src/components/midi/mappedParameterItem.tsx
src/components/midi/mappedParameterList.tsx
src/components/midi/midi.module.css
src/components/nav/index.tsx
src/components/nav/nav.module.css
src/components/parameter/item.tsx
src/lib/constants.ts
src/lib/types.ts
src/lib/util.ts
src/models/graph.ts
src/models/instance.ts
src/models/messageport.ts
src/models/parameter.ts
src/pages/files.tsx
src/pages/instances/[index].tsx
src/pages/midimappings.tsx
src/selectors/patchers.ts

This adds a Global MIDI Mapping view. Currently it's read-only apart from clearing the mapping but should be relatively straightforward to make it possible to inline edit the MIDI Channel and CCs.
I've added a button to the left sidebar for now to access this view, reasonable?
Setting to draft for now until editing in place.
Closes #171

Add Global MIDI Mapping View

---

src/actions/editor.ts
src/actions/graph.ts
src/actions/meta.ts
src/actions/sets.ts

Trigger meta data /coordinates deletion for GraphPatcherNodes when unloading a node, instance or clearing a set

---

server.py
src/actions/editor.ts
src/actions/graph.ts
src/actions/patchers.ts
src/actions/sets.ts
src/components/editor/index.tsx
src/components/editor/patcherNode.tsx
src/components/midi/mappedParameterItem.tsx
src/components/midi/mappedParameterList.tsx
src/components/nav/index.tsx
src/components/parameter/withSetViewActions.tsx
src/controller/oscqueryBridgeController.ts
src/lib/constants.ts
src/lib/util.ts
src/models/graph.ts
src/models/instance.ts
src/models/messageport.ts
src/models/parameter.ts
src/models/set.ts
src/pages/instances/[id].tsx
src/pages/instances/[index].tsx
src/pages/midimappings.tsx
src/reducers/graph.ts
src/reducers/patchers.ts
src/selectors/graph.ts
src/selectors/patchers.ts
src/selectors/sets.ts

In order to reduce complexity we can just refer to the instance index as id. OSCQuery stores it as a string AFAICT anyway and there isn't really a need to track both, an id and a numeric index around. Ideally this will also help with further simplifying the graph data structures once we move towards port groups as part of #176 
Note that this is a PR on top of #192

Dropped instance.index usage in favour of referring to it simply as id

---

src/actions/patchers.ts
src/actions/sets.ts
src/components/presets/index.tsx
src/components/presets/item.tsx
src/components/presets/save.tsx
src/components/setViews/create.tsx
src/components/setViews/drawer.tsx
src/components/setViews/item.tsx
src/components/setViews/paramModal.tsx
src/components/sets/index.tsx
src/components/sets/item.tsx
src/components/sets/save.tsx
src/pages/index.tsx
src/pages/instances/[id].tsx
src/pages/setviews.tsx
src/selectors/patchers.ts

This PR prevents overwriting existing presets (both on instance as well as set level), sets and setviews by ensuring name conflicts are marked as an error.
Note I made this PR on top of the views work to get uniqueness validation for SetViews in there already as well as resusing the `getUniqueName` util that was already in place here.
closes #147

Handle renaming conflicts

---

src/actions/graph.ts
src/controller/oscqueryBridgeController.ts
src/lib/constants.ts
src/lib/types.ts
src/models/graph.ts

Added a stopgap fix for #104 here that should address the issue.
However, I wonder if we should harden the port management further by simplifying it. The current code basically creates ports and nodes from `/rnbo/jack/info/ports/audio|midi` and then later on shuffles the nodes around once the properties are received in order to assign / maintain the correct group.
Not sure what your appetite for this is now @x37v. The frontend could do a lookup for the port id in order to determine `type` and `direction` but I wonder if adding the port `type` and `direction` to the entries in `/rnbo/jack/info/ports/properties` directly would make this much easier? Ideally managing / syncing the ports from the audio and midi entries becomes obsolete and we could solely manage port / node state based on the …

clean up nodes without ports when receiving port props

---

src/actions/editor.ts
src/components/editor/index.tsx
src/pages/index.tsx

Noticed a bug where we would propagate through the request from ReactFlow to delete edges when one hits backspace, albeit the user not having confirmed the instance deletion in the popup modal.
Got around this by using a custom, global hot key handler for the editor and solely operating based on EdgeChanges and NodeChanges in conjunction with the selection state.

Fix Edge Delete prior to Instance Delete confirmation

---

src/actions/datafiles.ts
src/actions/patchers.ts
src/actions/sets.ts
src/components/dataref/item.tsx
src/components/dataref/list.tsx
src/components/elements/editableTableCell.tsx
src/components/instance/datarefTab.tsx
src/components/instance/inportTab.tsx
src/components/instance/outportTab.tsx
src/components/patchers/managementView.tsx
src/controller/oscqueryBridgeController.ts
src/lib/dialogs.tsx
src/lib/util.ts
src/models/datafile.ts
src/models/dataref.ts
src/models/messageport.ts
src/reducers/datafiles.ts
src/selectors/datafiles.ts

Adds the UI for saving buffer contents as discussed with a `string` argument to the `save` endpoint. Note that this doesn't have any notification in place yet, will add that once #238 is merged.
Drafting for now given that it's still a WIP, also on the runner side.

Save Buffer Content

---

src/actions/recording.ts
src/controller/oscqueryBridgeController.ts

OK turns out the jack info state syncing "swallowed" the port property synchronization leading to nodes being unmovable and also prevented the channel count increments to immediately be reflected in the recording node in the graph view.
fixes #244 #226

Fix Port Property Updates
