Cycling74/rnbo-runner-panel

- src/components/editor/editor.module.css
> Increase Port label spacing

- src/actions/graph.ts
> Ensure to only consider nodes with "system" prefix as system nodes

- src/actions/graph.ts
- src/controller/oscqueryBridgeController.ts
- src/lib/types.ts
- src/models/graph.ts
- src/reducers/graph.ts
Uses new OSCQuery API for simpler connection state handling and enables system to system connections
Closes #53
> Simpler Connection management

- src/actions/graph.ts
- src/controller/oscqueryBridgeController.ts
- src/lib/types.ts
Note that currently new nodes don't necessarily have position information as we also don't know their runner assigned ID at creation time.
> Store Node position information in Set Meta data

- src/actions/settings.ts
- src/components/page/about.tsx
- src/components/page/page.module.css
- src/components/settings/index.tsx
- src/components/settings/list.tsx
- src/components/settings/settings.module.css
- src/models/config.ts
- src/reducers/settings.ts
- src/selectors/settings.ts
> Improved "About" and Empty "Audio" Settings when not owning the Jack config

- src/components/nav/index.tsx
- src/components/nav/link.tsx
- src/components/nav/nav.module.css
- src/pages/index.tsx
- src/selectors/graph.ts
> Improved handling of no patch and no device scenarios

- src/actions/graph.ts
- src/actions/settings.ts
- src/components/settings/index.tsx
- src/components/settings/item.tsx
- src/components/settings/list.tsx
- src/controller/oscqueryBridgeController.ts
- src/models/graph.ts
> Support Dynamic System Node updates

- src/actions/transport.ts
- src/components/header/index.tsx
- src/components/page/page.module.css
- src/components/page/transport.tsx
- src/controller/oscqueryBridgeController.ts
- src/lib/types.ts
- src/pages/_app.tsx
- src/reducers/index.ts
- src/reducers/transport.ts
- src/selectors/transport.ts
> added basic transport control ui

- src/components/page/endpoint.tsx
> Allow adjusting endpoint to reload page with new runner target

- src/components/editor/systemNode.tsx
> use jackname instead of id for system node display

- src/lib/settings.ts
- src/models/config.ts
- src/reducers/settings.ts
> Maintain control over setting and config sorting

- src/actions/graph.ts
> filter out new control nodes by comparing node name to patcher names

- src/components/patchers/index.tsx
- src/components/patchers/item.tsx
- src/components/presets/index.tsx
- src/components/sets/index.tsx
- src/pages/index.tsx
> Moved Patcher selection to drawer

- src/actions/instances.ts
- src/components/instance/instance.module.css
- src/components/instance/paramTab.tsx
- src/components/parameter/list.tsx
- src/lib/constants.ts
- src/lib/types.ts
- src/models/parameter.ts
- src/reducers/instances.ts
- src/selectors/instances.ts
Added a small menu to the param list to adjust sorting attr and order, currently supporting name and index
closes #113
> instances: added parameter list sorting options

- src/actions/instances.ts
- src/lib/types.ts
- src/models/instance.ts
> Support nested in and out ports

- server.py
> handle mapping to /instances/[index].html

- src/components/editor/index.tsx
> increase min and max zoom

- src/components/datafile/item.tsx
- src/components/datafile/uploadModal.tsx
> remove extra delete dialog

- src/components/header/cpu.module.css
- src/components/header/cpu.tsx
- src/components/header/index.tsx
> cpu meter with permanently shown CPU load in %

- src/actions/editor.ts
- src/actions/graph.ts
- src/components/editor/editor.module.css
- src/reducers/graph.ts
- src/selectors/graph.ts
> apply autolayout and fit graph into view upon initial load if no position data present

- src/actions/datafiles.ts
- src/actions/editor.ts
- src/actions/graph.ts
- src/actions/patchers.ts
- src/actions/sets.ts
- src/components/instance/datarefTab.tsx
- src/components/meta/metaEditorModal.tsx
- src/components/midi/mappedParameterItem.tsx
- src/components/parameter/withMidiActions.tsx
- src/components/presets/index.tsx
- src/components/presets/item.tsx
- src/components/setViews/drawer.tsx
- src/components/setViews/paramModal.tsx
- src/components/sets/index.tsx
- src/lib/dialogs.tsx
- src/pages/files.tsx
- src/pages/index.tsx
- src/pages/instances/[id].tsx
- src/pages/patchers.tsx
Follow up for #203 to unify dialogs and handle them in actions rather than in Component logic
> Consistent and Unified Dialogs

- src/components/setViews/drawer.tsx
> fixed leftover SetViews display label

- src/actions/sets.ts
- src/components/editor/saveGraphSplitButton.module.css
- src/components/editor/saveGraphSplitButton.tsx
- src/components/editor/setTitle.module.css
- src/components/editor/setTitle.tsx
- src/components/elements/responsiveButton.tsx
- src/components/sets/index.tsx
- src/components/sets/sets.module.css
- src/pages/index.tsx
> added "Save As" to Graph Drawer

- src/actions/sets.ts
- src/lib/util.ts
- src/models/parameter.ts
- src/models/set.ts
- src/selectors/patchers.ts
> use param.name for managing and identifying params in SetViews

- src/actions/patchers.ts
- src/components/instance/paramTab.tsx
- src/components/parameter/item.tsx
- src/components/parameter/withSetViewActions.tsx
- src/controller/oscqueryBridgeController.ts
- src/lib/types.ts
- src/models/parameter.ts
- src/selectors/patchers.ts
> Param Display Name support

- src/actions/sets.ts
- src/components/editor/saveGraphSplitButton.module.css
- src/components/editor/saveGraphSplitButton.tsx
- src/components/elements/responsiveButton.tsx
- src/pages/index.tsx
> improved dialogs for unsaved, new graphs & reloading an already loaded graph

- src/components/setViews/paramModal.tsx
> use param.label in parameter view modal

- src/actions/graph.ts
So this was an oversight and I could reproduce by:
* make a new graph and close the web interface
* export/run a patcher from RNBO
* reopen the web interface
* => node not moveable
Due to the removal of the port IO sync we ended up without node positions and just need to ensure all nodes have position data when updating the meta.
closes #226
> ensure node position data exists for all nodes when updating meta

- src/actions/patchers.ts
- src/components/dataref/item.tsx
- src/components/dataref/list.tsx
- src/components/instance/datarefTab.tsx
- src/components/instance/index.tsx
- src/components/meta/metaEditorModal.tsx
- src/controller/oscqueryBridgeController.ts
- src/lib/constants.ts
- src/lib/types.ts
- src/models/dataref.ts
- src/models/instance.ts
- src/pages/instances/[id].tsx
- src/reducers/patchers.ts
- src/selectors/patchers.ts
> Add Buffer Meta Editing

- src/actions/sets.ts
- src/components/sets/item.tsx
- src/components/sets/managementView.tsx
- src/components/settings/index.tsx
- src/controller/oscqueryBridgeController.ts
- src/lib/constants.ts
- src/lib/dialogs.tsx
- src/lib/types.ts
- src/lib/util.ts
- src/models/config.ts
- src/reducers/sets.ts
- src/selectors/sets.ts
Adds on top of the resource management PR (#233 ) by introducing a startup configuration dialogue to the Graph Resource management view
Closes #182
> Graph Startup Configuration

- src/actions/patchers.ts
- src/components/instance/index.tsx
- src/components/instance/inportTab.tsx
- src/components/instance/instance.module.css
- src/components/instance/outportTab.tsx
- src/components/messages/inport.tsx
- src/components/messages/inportList.tsx
- src/components/messages/outport.tsx
- src/components/messages/outportList.tsx
- src/components/messages/ports.module.css
- src/lib/constants.ts
- src/models/settings.ts
> Separare inport and outport device tabs and "bang" support

- src/components/parameter/item.tsx
- src/components/parameter/withInstanceNamePrefix.tsx
- src/components/parameter/withSetViewActions.tsx
- src/components/setViews/parameterList.tsx
- src/pages/setviews.tsx
> Display PatcherInstance names in set view param list
